SELECT * FROM MEDICAMENTO;
SELECT * FROM STOCKDISPONIBLE;

CREATE SEQUENCE SE_CODMEDICAMENTO
MINVALUE 1
START WITH 1
INCREMENT BY 1
NOMAXVALUE;

CREATE SEQUENCE SE_CODSTOCK
MINVALUE 1
START WITH 1
INCREMENT BY 1
NOMAXVALUE;

CREATE OR REPLACE PROCEDURE AGREGAR_MEDICAMENTOS
(P_NOMBRE_MED VARCHAR2, P_COMP_MED VARCHAR2,P_TIPO_MED 
VARCHAR2, P_GR_MED NUMBER)

IS
  BEGIN
    INSERT INTO Medicamento(codMedicamento,nombre,componentes,tipo,gramaje)
         VALUES (SE_CODMEDICAMENTO.NEXTVAL,P_NOMBRE_MED,P_COMP_MED, P_TIPO_MED,P_GR_MED);   
END;

BEGIN
AGREGAR_MEDICAMENTOS ('IBUPROFENO','c' ,'dolor' ,200);
END;

CREATE OR REPLACE PROCEDURE AGREGAR_STOCK  
(P_COD_MED NUMBER, P_CANT_MED NUMBER, P_FECHA_VENC DATE)
IS
  BEGIN
      INSERT INTO STOCKDISPONIBLE(CODSTOCK,CANTIDAD,FECVENCIMIENTO,MEDICAMENTO_CODMEDICAMENTO)VALUES (SE_CODSTOCK.NEXTVAL,P_CANT_MED,P_FECHA_VENC,P_COD_MED);   
END;

BEGIN
AGREGAR_STOCK (1,10,'10/05/2017');
END;

create or replace PROCEDURE LOGIN_FUNCIONARIO(P_USER VARCHAR2,P_PASS VARCHAR2, P_NOMBRE OUT VARCHAR2)

AS

BEGIN
   
    select fu.NOMBRE||' '||fu.APELLIDOP  INTO P_NOMBRE from FUNCIONARIO fu
    join USUARIO u 
    on fu.USUARIO_IDUSUARIO=u.IDUSUARIO
    where u."user"= P_USER AND u.PASSWORD=P_PASS;
    DBMS_OUTPUT.put_line(p_nombre); 
     
   exception
   when NO_DATA_FOUND then
   p_nombre := '1';
  
  --DBMS_OUTPUT.put_line(p_nombre);


END;
declare
v_v VARCHAR2(255);
BEGIN
LOGIN_FUNCIONARIO('TODY','TODY',v_v);
END;

create or replace PROCEDURE DESCONTAR_MEDICAMENTO 
   (P_COD NUMBER, P_TOTAL NUMBER)
IS
  BEGIN
 DECLARE
 V_STOCK NUMBER(8):=0;
 V_TOTAL NUMBER(8):=P_TOTAL;
 V_CANTIDAD NUMBER(8):=0;
 V_CANT2 NUMBER(8):=0;
  BEGIN
     FOR V_STOCK IN (SELECT * FROM STOCKDISPONIBLE ORDER BY CODSTOCK ASC)
       LOOP 
       SELECT CANTIDAD INTO V_CANTIDAD FROM STOCKDISPONIBLE WHERE CODSTOCK=V_STOCK.CODSTOCK;
       SELECT CANTIDAD-V_TOTAL INTO V_CANT2 FROM STOCKDISPONIBLE WHERE CODSTOCK=V_STOCK.CODSTOCK;
       V_TOTAL:=V_TOTAL-V_CANTIDAD;
       update STOCKDISPONIBLE set CANTIDAD=V_CANT2
         where CODSTOCK=V_STOCK.CODSTOCK;
       IF V_TOTAL<0 THEN
          EXIT;
       END IF;
       IF V_TOTAL>=0 THEN
         DELETE FROM STOCKDISPONIBLE WHERE CODSTOCK = V_STOCK.CODSTOCK;
       END IF;
     END LOOP;
  END;
END;
