DROP PROCEDURE  DESCONTAR_MEDICAMENTO;
DROP PROCEDURE AGREGAR_MEDICAMENTOS_STOCK;
DROP SEQUENCE SE_CODMEDICAMENTO;
DROP SEQUENCE SE_CODSTOCK;

delete usuario;
delete medicamento;
delete merma;
delete STOCKDISPONIBLE;
delete medico;
delete funcionario;
delete receta;
delete reserva;
delete paciente;
delete tutor;
delete preescripcion;



SELECT * FROM STOCKDISPONIBLE;

SELECT * FROM MEDICAMENTO;

CREATE SEQUENCE SE_CODMEDICAMENTO
MINVALUE 1
START WITH 1
INCREMENT BY 1
NOMAXVALUE;
 INSERT INTO MEDICAMENTO(CODMEDICAMENTO,NOMBRE,COMPONENTES,TIPO,GRAMAJE,FECVENCIMIENTO,CANTIDAD)
                 VALUES (SE_CODMEDICAMENTO.NEXTVAL,'ASPIRINA','A','B',100,'12/03/2017',10); 
CREATE SEQUENCE SE_CODSTOCK
MINVALUE 1
START WITH 1
INCREMENT BY 1
NOMAXVALUE;


INSERT INTO STOCKDISPONIBLE(CODSTOCK,TOTAL,MEDICAMENTO_CODMEDICAMENTO)VALUES (SE_CODSTOCK.NEXTVAL,10,1); 


CREATE OR REPLACE PROCEDURE AGREGAR_MEDICAMENTOS_STOCK  
(P_COD_MED NUMBER, P_NOMBRE_MED VARCHAR2, P_COMP_MED VARCHAR2,P_TIPO_MED 
VARCHAR2, P_GR_MED NUMBER, P_FECHA_VENC DATE, P_CANT_MED NUMBER,P_STOCK_MED NUMBER)

IS
  BEGIN
    INSERT INTO Medicamento(codMedicamento,nombre,componentes,tipo,gramaje,fecVencimiento,cantidad)
         VALUES (SE_CODMEDICAMENTO.NEXTVAL,P_NOMBRE_MED,P_COMP_MED, P_TIPO_MED,P_GR_MED,P_FECHA_VENC,P_CANT_MED);
           INSERT INTO STOCKDISPONIBLE(CODSTOCK,TOTAL,MEDICAMENTO_CODMEDICAMENTO)VALUES (SE_CODSTOCK.NEXTVAL,P_CANT_MED,P_COD_MED);   
END;

BEGIN
AGREGAR_MEDICAMENTOS_STOCK (1,'PARACETAMOL','b' ,'dolor' ,600,'20/03/2018',30,2);
END;

CREATE OR REPLACE PROCEDURE DESCONTAR_MEDICAMENTO 
   (P_COD NUMBER, P_TOTAL NUMBER)

IS
  BEGIN
 DECLARE
 V_CANTIDAD NUMBER(8):=0;
 V_CANT2 NUMBER(8):=0;
 V_COD NUMBER(8):=0;
  BEGIN
     SELECT MIN(CODSTOCK) INTO V_COD FROM STOCKDISPONIBLE WHERE MEDICAMENTO_CODMEDICAMENTO=P_COD;
     SELECT TOTAL-P_TOTAL INTO V_CANTIDAD FROM STOCKDISPONIBLE WHERE CODSTOCK=V_COD;
     IF V_CANTIDAD<=0 THEN
       DELETE FROM STOCKDISPONIBLE WHERE CODSTOCK = V_COD;
       SELECT MIN(CODSTOCK) INTO V_COD FROM STOCKDISPONIBLE WHERE MEDICAMENTO_CODMEDICAMENTO=P_COD;
       SELECT TOTAL-ABS (V_CANTIDAD) INTO V_CANT2 FROM STOCKDISPONIBLE WHERE CODSTOCK=V_COD;
       update STOCKDISPONIBLE set TOTAL=V_CANT2
       where CODSTOCK=V_COD;
     ELSE
       update STOCKDISPONIBLE set TOTAL=V_CANTIDAD
       where CODSTOCK=V_COD;
     END IF;
  END;
END;

BEGIN
  DESCONTAR_MEDICAMENTO(3,20);
END;

SELECT ABS(TOTAL-10)as total FROM STOCKDISPONIBLE WHERE CODSTOCK=4;