SELECT * FROM STOCKDISPONIBLE;
INSERT INTO STOCKDISPONIBLE(CODSTOCK,TOTAL,MEDICAMENTO_CODMEDICAMENTO)VALUES (3,10,3); 
CREATE OR REPLACE PROCEDURE AGREGAR_MEDICAMENTOS_STOCK  
(P_COD_MED NUMBER, P_NOMBRE_MED VARCHAR2, P_COMP_MED VARCHAR2,P_TIPO_MED VARCHAR2, P_GR_MED NUMBER, P_FECHA_VENC DATE, P_CANT_MED NUMBER,P_STOCK_MED NUMBER)

IS
  BEGIN
    INSERT INTO Medicamento(codMedicamento,nombre,componentes,tipo,gramaje,fecVencimiento,cantidad)
         VALUES (P_COD_MED,P_NOMBRE_MED,P_COMP_MED, P_TIPO_MED,P_GR_MED,P_FECHA_VENC,P_CANT_MED);
         INSERT INTO STOCKDISPONIBLE(CODSTOCK,TOTAL,MEDICAMENTO_CODMEDICAMENTO)VALUES (P_STOCK_MED,P_CANT_MED,P_COD_MED);   
END;

BEGIN
AGREGAR_MEDICAMENTOS_STOCK  
--(2 , 'IBUPROFENO' , 'ACIDO' ,'ANALGESICO' , 500,'12/03/2018',10 ,2 );
--(3 , 'PARACETAMOL' , 'A' ,'ANALGESICO' , 500,'12/03/2018',10 ,3 );
(3 , 'PARACETAMOL' , 'A' ,'ANALGESICO' , 500,'12/03/2018',10 ,4 );
END;

CREATE OR REPLACE PROCEDURE DESCONTAR_MEDICAMENTO 
(P_COD NUMBER, P_TOTAL NUMBER)

IS

  BEGIN
 DECLARE
 V_CANTIDAD NUMBER(8):=0;
 V_CANT2 NUMBER(8):=0;
 V_COD NUMBER(8):=0;
  BEGIN
     SELECT MIN(CODSTOCK) INTO V_COD FROM STOCKDISPONIBLE WHERE MEDICAMENTO_CODMEDICAMENTO=P_COD;
     SELECT TOTAL-P_TOTAL INTO V_CANTIDAD FROM STOCKDISPONIBLE WHERE CODSTOCK=V_COD;
     IF V_CANTIDAD<=0 THEN
       DELETE FROM STOCKDISPONIBLE WHERE CODSTOCK = V_COD;
       SELECT MIN(CODSTOCK) INTO V_COD FROM STOCKDISPONIBLE WHERE MEDICAMENTO_CODMEDICAMENTO=P_COD;
       SELECT TOTAL-ABS (V_CANTIDAD) INTO V_CANT2 FROM STOCKDISPONIBLE WHERE CODSTOCK=V_COD;
       update STOCKDISPONIBLE set TOTAL=V_CANT2
       where CODSTOCK=V_COD ;
     ELSE
       update STOCKDISPONIBLE set TOTAL=V_CANTIDAD
       where CODSTOCK=V_COD ;
     END IF;
  END;
END;

BEGIN
  DESCONTAR_MEDICAMENTO(3,7);
END;

SELECT ABS(TOTAL-10) FROM STOCKDISPONIBLE WHERE CODSTOCK=3;