CREATE OR REPLACE PROCEDURE AGREGAR_MEDICAMENTOS
(P_NOMBRE_MED VARCHAR2, P_COMP_MED VARCHAR2,P_TIPO_MED 
VARCHAR2, P_GR_MED NUMBER, P_FECHA_VENC DATE, P_CANT_MED NUMBER)

IS
  BEGIN
    INSERT INTO Medicamento(codMedicamento,nombre,componentes,tipo,gramaje,fecVencimiento,cantidad)
         VALUES (SE_CODMEDICAMENTO.NEXTVAL,P_NOMBRE_MED,P_COMP_MED, P_TIPO_MED,P_GR_MED,P_FECHA_VENC,P_CANT_MED);   
END;

BEGIN
AGREGAR_MEDICAMENTOS ('IBUPROFENO','c' ,'dolor' ,200,'20/03/2018',30);
END;

CREATE OR REPLACE PROCEDURE AGREGAR_STOCK  
(P_COD_MED NUMBER, P_CANT_MED NUMBER)
IS
  BEGIN
      INSERT INTO STOCKDISPONIBLE(CODSTOCK,TOTAL,MEDICAMENTO_CODMEDICAMENTO)VALUES (SE_CODSTOCK.NEXTVAL,P_CANT_MED,P_COD_MED);   
END;

BEGIN
AGREGAR_STOCK (7,10);
END;

create or replace PROCEDURE DESCONTAR_MEDICAMENTO 
   (P_COD NUMBER, P_TOTAL NUMBER)
IS
  BEGIN
 DECLARE
 V_CANTIDAD NUMBER(8):=0;
 V_CANT2 NUMBER(8):=0;
 V_COD NUMBER(8):=0;
  BEGIN
     SELECT MIN(CODSTOCK) INTO V_COD FROM STOCKDISPONIBLE WHERE MEDICAMENTO_CODMEDICAMENTO=P_COD;
     SELECT CANTIDAD-P_TOTAL INTO V_CANTIDAD FROM STOCKDISPONIBLE WHERE CODSTOCK=V_COD;
     update STOCKDISPONIBLE set CANTIDAD=V_CANTIDAD
     where CODSTOCK=V_COD;
     IF V_CANTIDAD=0 THEN
       DELETE FROM STOCKDISPONIBLE WHERE CODSTOCK = V_COD;
     END IF;
     IF V_CANTIDAD<0 THEN
       DELETE FROM STOCKDISPONIBLE WHERE CODSTOCK = V_COD;
       SELECT MIN(CODSTOCK) INTO V_COD FROM STOCKDISPONIBLE WHERE MEDICAMENTO_CODMEDICAMENTO=P_COD;
       SELECT CANTIDAD-ABS (V_CANTIDAD) INTO V_CANT2 FROM STOCKDISPONIBLE WHERE CODSTOCK=V_COD;
       update STOCKDISPONIBLE set CANTIDAD=V_CANT2
       where CODSTOCK=V_COD;
     END IF;
  END;
END;

BEGIN
  DESCONTAR_MEDICAMENTO(1,10);
END;

SELECT * FROM MEDICAMENTO;
SELECT * FROM STOCKDISPONIBLE;
DELETE FROM STOCKDISPONIBLE WHERE CODSTOCK=11;